## Вправа 1 
Вводиться число n. Вивести масив розміру n×n, в
якому по діагоналі йдуть числа від 1 до n, а інші числа дорівнюють 0.

In [1]:
import numpy as np

In [26]:
n = int(input("Введіть число n: "))

Введіть число n:  100


In [27]:
%%time
matrix_a = np.zeros((n, n), dtype=int)
np.fill_diagonal(matrix_a, np.arange(1, n+1))

CPU times: total: 0 ns
Wall time: 0 ns


In [28]:
%%time
matrix_b = [[i + 1 if i == j else 0 for j in range(n)] for i in range(n)]

CPU times: total: 0 ns
Wall time: 1 ms


In [29]:
n = int(input("Введіть число n: "))

Введіть число n:  5


In [30]:
%%time
matrix_a = np.zeros((n, n), dtype=int)
np.fill_diagonal(matrix_a, np.arange(1, n+1))

print("Масив з використанням NumPy:")
print(matrix_a)

Масив з використанням NumPy:
[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]
CPU times: total: 0 ns
Wall time: 0 ns


In [31]:
%%time
matrix_b = [[i + 1 if i == j else 0 for j in range(n)] for i in range(n)]

print("Масив з використанням ітерацій:")
for row in matrix_b:
    print(row)

Масив з використанням ітерацій:
[1, 0, 0, 0, 0]
[0, 2, 0, 0, 0]
[0, 0, 3, 0, 0]
[0, 0, 0, 4, 0]
[0, 0, 0, 0, 5]
CPU times: total: 0 ns
Wall time: 0 ns
