## Вправа 11
Створити масив одиниць розміром n×n та додати до
нього «рамку», що утворюється з 0.

In [1]:
import numpy as np

In [2]:
n = int(input("Введіть розмір масиву n: "))

Введіть розмір масиву n:  4


In [5]:
%%time
matrix_a = np.ones((n+2, n+2), dtype=int)

matrix_a[0, :] = 0
matrix_a[-1, :] = 0
matrix_a[:, 0] = 0
matrix_a[:, -1] = 0

print("Масив з використанням NumPy:")
print(matrix_a)

Масив з використанням NumPy:
[[0 0 0 0 0 0]
 [0 1 1 1 1 0]
 [0 1 1 1 1 0]
 [0 1 1 1 1 0]
 [0 1 1 1 1 0]
 [0 0 0 0 0 0]]
CPU times: total: 0 ns
Wall time: 0 ns


In [7]:
%%time
matrix_b = [[1] * (n+2) for _ in range(n+2)]

for i in range(n+2):
    matrix_b[i][0] = 0
    matrix_b[i][-1] = 0
    matrix_b[0][i] = 0
    matrix_b[-1][i] = 0

print("Масив з використанням ітерацій:")
for row in matrix_b:
    print(row)

Масив з використанням ітерацій:
[0, 0, 0, 0, 0, 0]
[0, 1, 1, 1, 1, 0]
[0, 1, 1, 1, 1, 0]
[0, 1, 1, 1, 1, 0]
[0, 1, 1, 1, 1, 0]
[0, 0, 0, 0, 0, 0]
CPU times: total: 0 ns
Wall time: 0 ns
