## Вправа 2
Вводиться число n. Розставити 1 та 0 у шаховому порядку, починаючи з 1 в матриці розміром n×n, використовуючи слайсінг.

In [13]:
import numpy as np

In [14]:
n = int(input("Введіть розмір матриці (n): "))

Введіть розмір матриці (n):  5


In [21]:
%%time
board = np.zeros((n, n), dtype=int)

board[1::2, ::2] = 1
board[::2, 1::2] = 1

print("Шахова дошка розміром", n, "x", n, "з 1 та 0:")
print(board)

Шахова дошка розміром 5 x 5 з 1 та 0:
[[0 1 0 1 0]
 [1 0 1 0 1]
 [0 1 0 1 0]
 [1 0 1 0 1]
 [0 1 0 1 0]]
CPU times: total: 0 ns
Wall time: 991 µs


In [19]:
%%time
def print_board(board):
    for row in board:
        print("[", end="")
        for i in range(len(row)):
            if i == len(row) - 1:
                print(row[i], end="")
            else:
                print(row[i], end=" ")
        print("]")


board = []

for i in range(n):
    row = []
    for j in range(n):
        if (i + j) % 2 == 0:
            row.append(0)
        else:
            row.append(1)
    board.append(row)

print("Шахова дошка розміром", n, "x", n, "з 0 та 1:")
print_board(board)

Шахова дошка розміром 5 x 5 з 0 та 1:
[0 1 0 1 0]
[1 0 1 0 1]
[0 1 0 1 0]
[1 0 1 0 1]
[0 1 0 1 0]
CPU times: total: 0 ns
Wall time: 999 µs
