## Вправа 21
Ввести числа n і m. Згенерувати матрицю n×n
випадкових цілих елементів з діапазону [0, m]. Замінити всі
максимальні елементи цієї матриці на протилежні за знаком.

In [1]:
import numpy as np

In [15]:
n = int(input())
m = int(input())
matrix = np.random.randint(0, m+1, size=(n, n))
print("Матриця:")
print(matrix)

 4
 10


Матриця:
[[1 7 5 7]
 [1 9 7 7]
 [9 6 4 9]
 [7 7 3 8]]


In [18]:
%%time

matrix_a = matrix.copy()
max_value = np.max(matrix_a)
matrix_a[matrix_a == max_value] *= -1

print("Матриця з використанням NumPy:")
print(matrix_a)

Матриця з використанням NumPy:
[[ 1  7  5  7]
 [ 1 -9  7  7]
 [-9  6  4 -9]
 [ 7  7  3  8]]
CPU times: total: 0 ns
Wall time: 990 µs


In [17]:
%%time

matrix_a = matrix.copy()
max_value = max(max(row) for row in matrix_a)

for i in range(n):
    for j in range(n):
        if matrix_a[i][j] == max_value:
            matrix_a[i][j] *= -1

print("Матриця з використанням ітерацій:")
for row in matrix_a:
    print(row)

Матриця з використанням ітерацій:
[1 7 5 7]
[ 1 -9  7  7]
[-9  6  4 -9]
[7 7 3 8]
CPU times: total: 0 ns
Wall time: 1 ms
