Вправа 3.
Вводяться 4 числа n, m, r, c. Вивести масив розміру n×m, в якому в кожному рядку з номером r і в кожному стовпчику з номером c стоять 0, а інші елементи дорівнюють 1.

In [3]:
import numpy as np

In [1]:
n = int(input("Введіть n: "))
m = int(input("Введіть m: "))
r = int(input("Введіть r: "))
c = int(input("Введіть c: "))

Введіть n:  6
Введіть m:  7
Введіть r:  2
Введіть c:  3


In [4]:
%%time
array_np = np.ones((n, m), dtype=int)
array_np[::r, :] = 0
array_np[:, ::c] = 0

print("Масив за допомогою NumPy:")
print(array_np)

Масив за допомогою NumPy:
[[0 0 0 0 0 0 0]
 [0 1 1 0 1 1 0]
 [0 0 0 0 0 0 0]
 [0 1 1 0 1 1 0]
 [0 0 0 0 0 0 0]
 [0 1 1 0 1 1 0]]
CPU times: total: 0 ns
Wall time: 0 ns


In [5]:
%%time
array_iter = [[0 if i % r == 0 or j % c == 0 else 1 for j in range(m)] for i in range(n)] 
 
print("Масив за допомогою ітеративних конструкцій:")
for row in array_iter:
    print(row)

Масив за допомогою ітеративних конструкцій:
[0, 0, 0, 0, 0, 0, 0]
[0, 1, 1, 0, 1, 1, 0]
[0, 0, 0, 0, 0, 0, 0]
[0, 1, 1, 0, 1, 1, 0]
[0, 0, 0, 0, 0, 0, 0]
[0, 1, 1, 0, 1, 1, 0]
CPU times: total: 0 ns
Wall time: 0 ns
