## Вправа 4 
Вводяться числа n і m. Вивести масив розміру n×m, в якому у першому рядку (рядок з нулевим індексом) йдуть числа від 0 до m–1, а всі інші елементи матриці дорівнюють 0.

In [1]:
import numpy as np

In [2]:
n = int(input())
m = int(input())

 3
 4


In [5]:
%%time
array = np.zeros((n, m), dtype=int)
array[0] = np.arange(m)

print("Масив розміром", n, "x", m, ":")
print(array)

Масив розміром 3 x 4 :
[[0 1 2 3]
 [0 0 0 0]
 [0 0 0 0]]
CPU times: total: 0 ns
Wall time: 0 ns


In [6]:
%%time
array = [[0] * m for _ in range(n)]
array[0] = list(range(m))

print("Масив розміром", n, "x", m, ":")
for row in array:
    print(row)

Масив розміром 3 x 4 :
[0, 1, 2, 3]
[0, 0, 0, 0]
[0, 0, 0, 0]
CPU times: total: 0 ns
Wall time: 0 ns
