Обчислити значення матричного виразу
- а) з використанням універсальних функцій бібліотеки NumPy.
- b) за допомогою ітеративних конструкцій (з використанням циклів, спискових включень тощо).
- с) для обох випадків підрахувати час виконання скрипту та зробити висновок.

Порівняти всі рішення за допомогою функції numpy.allclose().

$$
    3(A^2 - B^2) - 2AB, де 
    A = 
    \begin{pmatrix}
      4 & 2 & 1 \\
      3 & -2 & 0 \\
      0 & 1 & 2 \\
    \end{pmatrix}, 
    B = 
    \begin{pmatrix}
      2 & 0 & 2 \\
      5 & -7 & -2 \\
      1 & 0 & -1 \\
    \end{pmatrix}
$$

In [28]:
import numpy as np
import time

In [29]:
A = np.array([[4, 2, 1],
              [3, -2, 0],
              [0, 1, 2]])

B = np.array([[2, 0, 2],
              [5, -7, -2],
              [1, 0, -1]])

In [43]:
%%time
expression_result_np = 3 * (A @ A - B @ B) - 2 * A @ B
print("Результат за допомогою NumPy:")
print(expression_result_np)

Результат за допомогою NumPy:
[[  10   43    6]
 [ 107 -145  -89]
 [  -8   14   11]]
CPU times: total: 0 ns
Wall time: 0 ns


In [44]:
%%time
rows, cols = A.shape
expression_result_iterative = np.zeros((rows, cols), dtype=int)

def scalar_product(vector1, vector2):
    return sum(v1 * v2 for v1, v2 in zip(vector1, vector2))

for i in range(rows):
    for j in range(cols):
        term1 = 3 * (scalar_product(A[i, :], A[:, j]) - scalar_product(B[i, :], B[:, j]))
        term2 = 2 * scalar_product(A[i, :], B[:, j])
        expression_result_iterative[i, j] = term1 - term2
        
print("Результат за допомогою ітеративних конструкцій:")
print(expression_result_iterative)

Результат за допомогою ітеративних конструкцій:
[[  10   43    6]
 [ 107 -145  -89]
 [  -8   14   11]]
CPU times: total: 0 ns
Wall time: 999 µs


In [45]:
print("Порівняння результатів:", np.allclose(expression_result_np, expression_result_iterative))

Порівняння результатів: True
